# Imagen base ligera de Python
FROM python:3.11-slim

# Crear directorio de trabajo
WORKDIR /app

# Copiar solo las dependencias primero (para cache de pip)
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto donde correrá la app
EXPOSE 8000

# Comando para iniciar la API en modo desarrollo
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
