name: Build and Push Backend Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - 'backend/**'
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install -r requirements.txt
          pip install pytest
      
      - names: Running pytest
        working-directory: ./backend
        run: |
          pytest test_main.py
        

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tags
        id: vars
        run: |
          # Detectar si es un tag o un push normal
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}/backend:${{ env.TAG }} ./backend

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}/backend:${{ env.TAG }}
